name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - plotly
  - lxml
  - folium
  - requests
  - scrapy
  - geoplot
  - geopandas
  - Gym
  - pip
  - pip:
    - chart_studio
